name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Test and Coverage
        run: go test -cover ./...

  stype:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Style check
        run: test -z $(go fmt ./...) && echo $?
      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: run staticcheck
        run: staticcheck ./...
